jobs:
  add-reviews:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: kentaro-m/auto-assign-action@v1.1.2
      with:
        configuration-path: .github/auto_assign.yml
name: Auto Reviewer
on:
  repository_dispatch:
    types: trigger-ga___Auto_Review.yml
